title: Seth C. Oranburg
description: Law Professor, Scholar & Educator
baseurl: ""
url: "https://oranburg.law"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
future: true

# Exclude files from Jekyll build output
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
